#!/usr/bin/env python3
"""Turn the C# fences in the guides into a project the compiler can judge.

The guides are the single source of truth: nothing here copies a snippet, so a
snippet and its compiled counterpart cannot drift. Each ```csharp fence becomes
one method, which is what lets two snippets in the same guide both declare `cv`
without colliding. `using` lines are hoisted to the top of the generated file, so
a fence inherits the namespaces an earlier fence in the same guide opened --
exactly the way a reader reads the page.

Symbols the prose introduces without showing them (`trainingDocuments`,
`corpusVectors`, ...) come from the hand-written partial classes in
samples/DataNet.DocSnippets/SnippetContext.cs. That file is scaffolding, not a
copy of any snippet.

A fence that genuinely cannot compile opts out with an HTML comment on the line
before it:

    <!-- docs-compile: skip - reason a reviewer can disagree with -->

A marker that is not followed by a fence is an error: an opt-out that stopped
applying must not go unnoticed.

Usage:
    python3 tools/extract_doc_snippets.py [--check]

--check reports what it would generate and writes nothing.
"""

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = REPO / "samples" / "DataNet.DocSnippets" / "Generated"
SOURCES = ["README.md", "docs/guides/*.md"]

FENCE = re.compile(r"^```csharp[ \t]*\n(.*?)^```[ \t]*$", re.S | re.M)
# A trailing comment is common in a guide ("using DataNet.Text;  // TextElement"),
# and must not stop the line being recognised as a directive to hoist -- left in
# a method body it would parse as a `using` statement.
USING = re.compile(r"^using +[A-Za-z_][A-Za-z0-9_.]* *; *(//.*)?$")
SKIP = re.compile(r"^<!--\s*docs-compile:\s*skip\s*[-—:]?\s*(?P<reason>.*?)\s*-->\s*$")

HEADER = """// <auto-generated />
//
// Extracted from {source} by tools/extract_doc_snippets.py.
// Do not edit: edit the Markdown. This file is regenerated and git-ignored.
"""


def class_name(path: pathlib.Path) -> str:
    """A C# identifier from a file name: migrating-from-rapidfuzz.md -> MigratingFromRapidfuzz."""
    stem = path.stem.replace("_", "-")
    return "".join(part[:1].upper() + part[1:] for part in stem.split("-") if part)


def sources() -> list[pathlib.Path]:
    found: list[pathlib.Path] = []
    for pattern in SOURCES:
        if "*" in pattern:
            found.extend(sorted(REPO.glob(pattern)))
        else:
            found.append(REPO / pattern)
    return found


def line_of(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def skip_reason(text: str, fence_start: int) -> str | None:
    """The opt-out marker on the line immediately above the fence, if any."""
    preceding = text[:fence_start].rstrip("\n").rsplit("\n", 1)
    match = SKIP.match(preceding[-1].strip()) if preceding else None
    return (match.group("reason") or "no reason given") if match else None


def orphan_markers(text: str) -> list[int]:
    """Lines carrying an opt-out marker that no C# fence follows."""
    orphans = []
    lines = text.splitlines()
    for number, line in enumerate(lines, start=1):
        if SKIP.match(line.strip()) and not lines[number:number + 1] == ["```csharp"]:
            orphans.append(number)
    return orphans


def render(path: pathlib.Path, text: str) -> tuple[str, int, list[tuple[int, str]]]:
    usings: list[str] = []
    methods: list[str] = []
    skipped: list[tuple[int, str]] = []
    compiled = 0

    for index, match in enumerate(FENCE.finditer(text)):
        line = line_of(text, match.start())
        reason = skip_reason(text, match.start())
        if reason is not None:
            skipped.append((line, reason))
            continue

        body: list[str] = []
        for source_line in match.group(1).splitlines():
            if USING.match(source_line):
                if source_line.strip() not in usings:
                    usings.append(source_line.strip())
            else:
                body.append(source_line)

        while body and not body[0].strip():
            body.pop(0)
        while body and not body[-1].strip():
            body.pop()

        indented = "\n".join(f"        {b}" if b.strip() else "" for b in body)
        relative = path.relative_to(REPO).as_posix()
        methods.append(
            f"    /// <summary>The C# fence at {relative}:{line}.</summary>\n"
            f"    public void Snippet{index}()\n    {{\n{indented}\n    }}\n"
        )
        compiled += 1

    if compiled == 0:
        return "", 0, skipped

    document = HEADER.format(source=path.relative_to(REPO).as_posix())
    document += "\n" + "\n".join(sorted(usings)) + "\n" if usings else "\n"
    document += f"\nnamespace DataNet.DocSnippets;\n\ninternal sealed partial class {class_name(path)}\n{{\n"
    document += "\n".join(methods)
    document += "}\n"
    return document, compiled, skipped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report without writing")
    arguments = parser.parse_args()

    failures: list[str] = []
    written = 0
    compiled = 0
    skipped: list[tuple[str, int, str]] = []

    if not arguments.check:
        if OUTPUT.exists():
            for stale in OUTPUT.glob("*.cs"):
                stale.unlink()
        OUTPUT.mkdir(parents=True, exist_ok=True)

    for path in sources():
        if not path.exists():
            failures.append(f"{path.relative_to(REPO)}: listed in SOURCES but missing")
            continue
        text = path.read_text(encoding="utf-8")

        for line in orphan_markers(text):
            failures.append(
                f"{path.relative_to(REPO)}:{line}: a 'docs-compile: skip' marker that no "
                "```csharp fence follows. Remove it, or move it back above its fence."
            )

        document, count, opted_out = render(path, text)
        compiled += count
        skipped.extend((path.relative_to(REPO).as_posix(), line, reason) for line, reason in opted_out)
        if document and not arguments.check:
            (OUTPUT / f"{class_name(path)}.g.cs").write_text(document, encoding="utf-8")
            written += 1

    print(f"snippets compiled : {compiled}")
    print(f"snippets opted out: {len(skipped)}")
    for source, line, reason in skipped:
        print(f"  {source}:{line} — {reason}")
    if not arguments.check:
        print(f"files written     : {written} in {OUTPUT.relative_to(REPO)}")

    for failure in failures:
        print(f"::error::{failure}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
