#!/usr/bin/env python3
"""Generate the .globalconfig that raises the Sonar rules the analyzer package ships disabled.

SonarAnalyzer.CSharp enables a subset of its own rules by default; the SonarCloud
quality profile enables a different set. Rules in the second and not the first are
invisible to `dotnet build` and blocking at the quality gate, which is a three-minute
round trip per finding (issue #109).

Two inputs, both cheap:

  * the profile's active rules, from one anonymous SonarCloud call -- the project is
    public, so no token is involved and anyone who clones this repository can run it;
  * `runs[].tool.driver.rules[]` of a SARIF v2 error log, where the compiler itself
    declares which rules are enabled by default.

The intersection is written as severity entries. `warning`, not `error`:
TreatWarningsAsErrors already decides whether a finding stops the build, and one
lever for that decision is enough.
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
import urllib.request
from pathlib import Path

DEFAULT_API = "https://sonarcloud.io/api"
ORGANIZATION = "cyrilb1531"
PROJECT = "CyrilB1531_data.net"
LANGUAGE = "cs"
REPOSITORY = "csharpsquid"

RULE_ID = re.compile(r"^S\d+$")
EXIT_DRIFT = 1
EXIT_UNREACHABLE = 2
EXIT_INPUT_MISSING = 3
EXIT_TRUNCATED = 4

ROOT = Path(__file__).resolve().parent.parent


def fetch(url: str) -> dict:
    """One GET, or a clean failure naming the URL."""
    with urllib.request.urlopen(url, timeout=30) as response:  # noqa: S310 - fixed https host
        return json.loads(response.read().decode("utf-8"))


def profile_key(api: str) -> str:
    """The C# profile associated with *this project*, not the organization's default."""
    url = f"{api}/qualityprofiles/search?organization={ORGANIZATION}&project={PROJECT}"
    for profile in fetch(url)["profiles"]:
        if profile["language"] == LANGUAGE:
            return profile["key"]
    raise LookupError(f"no {LANGUAGE} quality profile is associated with {PROJECT}")


class TruncatedResponse(RuntimeError):
    """rules/search reported more rules than the page it sent back."""


def active_rules(payload: dict) -> set[str]:
    """The rule ids the profile activates, without the repository prefix."""
    total, rules = payload["total"], payload["rules"]
    if total > len(rules):
        raise TruncatedResponse(
            f"rules/search reports total={total} but this response carries only "
            f"{len(rules)} rules: the page (ps={payload.get('ps', '?')}) is smaller than "
            "the profile. Raise ps past the profile size or paginate with p=2, 3, ... "
            "-- the intersection below would otherwise silently drop the rules that fell "
            "off the page, and a build enforcing less than the quality gate is exactly "
            "the failure this generator exists to prevent."
        )
    return {
        key.split(":", 1)[1]
        for key in (rule["key"] for rule in rules)
        if key.startswith(f"{REPOSITORY}:")
    }


def disabled_rules(error_log: Path) -> set[str]:
    """The rule ids the analyzer package declares and ships disabled."""
    # utf-8-sig: the compiler writes a byte-order mark.
    document = json.loads(error_log.read_text(encoding="utf-8-sig"))
    disabled: set[str] = set()
    for run in document["runs"]:
        for rule in run["tool"]["driver"].get("rules", []):
            enabled = rule.get("defaultConfiguration", {}).get("enabled")
            if enabled is False and RULE_ID.match(rule["id"]):
                disabled.add(rule["id"])
    return disabled


def delta(active: set[str], disabled: set[str]) -> list[str]:
    """Active on the server and disabled in the package, in rule-number order."""
    return sorted(active & disabled, key=lambda rule: int(rule[1:]))


def render(rules: list[str], profile_key: str, analyzer_version: str) -> str:
    """The file, deterministic and timestamp-free so it can be drift-checked."""
    lines = [
        "is_global = true",
        "",
        "# Generated by tools/generate_sonar_globalconfig.py -- do not edit by hand.",
        "#",
        f"# The rules SonarCloud's profile {profile_key} activates for {PROJECT} and that",
        f"# SonarAnalyzer.CSharp {analyzer_version} ships disabled, so that a finding fails the",
        "# build on the machine that wrote the code rather than the quality gate three",
        "# minutes after the push. See docs/decisions/0015-sonar-rules-in-the-build.md and",
        "# issue #109.",
        "#",
        "# warning, not error: TreatWarningsAsErrors in the root Directory.Build.props is",
        "# what turns a finding into a failure, and two levers for one decision is one too",
        "# many.",
        "",
    ]
    lines += [f"dotnet_diagnostic.{rule}.severity = warning" for rule in rules]
    return "\n".join(lines) + "\n"


def analyzer_version() -> str:
    """The pin the root Directory.Build.props carries, quoted in the header."""
    text = (ROOT / "Directory.Build.props").read_text(encoding="utf-8")
    match = re.search(r"<DataNetSonarAnalyzerVersion>([^<]+)</", text)
    if match is None:
        raise LookupError("Directory.Build.props declares no DataNetSonarAnalyzerVersion")
    return match.group(1)


def build(args: argparse.Namespace) -> tuple[str, str]:
    if args.rules is not None:
        payload = json.loads(Path(args.rules).read_text(encoding="utf-8"))
        key = "(fixture)"
    else:
        key = profile_key(args.api)
        payload = fetch(
            f"{args.api}/rules/search?organization={ORGANIZATION}&qprofile={key}"
            f"&activation=true&languages={LANGUAGE}&ps=500")
    rules = delta(active_rules(payload), disabled_rules(Path(args.error_log)))
    return render(rules, key, analyzer_version()), key


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--error-log", required=True, help="SARIF v2 error log from a build")
    parser.add_argument("--output", default=str(ROOT / ".globalconfig"))
    parser.add_argument("--rules", help="a saved rules/search response, instead of calling the API")
    parser.add_argument("--api", default=DEFAULT_API)
    parser.add_argument("--check", action="store_true", help="compare instead of writing")
    args = parser.parse_args(argv)

    try:
        expected, key = build(args)
    except TruncatedResponse as error:
        print(str(error), file=sys.stderr)
        return EXIT_TRUNCATED
    except OSError as error:
        if error.filename is not None:
            # A local --error-log/--rules problem -- missing, unreadable, whatever
            # strerror says -- carries the path that failed. Route every one of them
            # here, not the network: must not read as "the API is down", which sends
            # whoever is debugging it the wrong way.
            print(f"cannot read {error.filename}: {error.strerror}", file=sys.stderr)
            return EXIT_INPUT_MISSING
        # urllib.error.URLError and TimeoutError are both already OSError subclasses,
        # and neither carries a filename: this is the network, not a local file.
        # The failure that must not look like drift: the file is fine, the network is not.
        print(f"could not reach {args.api}: {error}", file=sys.stderr)
        return EXIT_UNREACHABLE

    target = Path(args.output)
    if not args.check:
        target.write_text(expected, encoding="utf-8")
        print(f"{target}: {expected.count('dotnet_diagnostic.')} rules from profile {key}")
        return 0

    actual = target.read_text(encoding="utf-8") if target.exists() else ""
    if actual == expected:
        print(f"{target} matches profile {key}")
        return 0
    print("".join(difflib.unified_diff(
        actual.splitlines(keepends=True), expected.splitlines(keepends=True),
        fromfile=str(target), tofile="regenerated")))
    return EXIT_DRIFT


if __name__ == "__main__":
    sys.exit(main())
